# Generated by Django 3.2.12 on 2022-11-28 02:02

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookerprofile',
            name='user',
            field=models.OneToOneField(default=authentication.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='bookerprofile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
