# Generated by Django 3.2.12 on 2022-02-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, unique=True)),
                ('destination', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
