# Generated by Django 3.2.12 on 2022-11-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('payed', 'payed'), ('pending', 'pending'), ('received', 'received'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=50),
        ),
    ]
