# Generated by Django 3.2.12 on 2022-02-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('[x.source for x in jj]', '[x.source for x in jj]')], max_length=50),
        ),
    ]
