# Generated by Django 3.2.12 on 2023-01-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('received', 'received'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=50),
        ),
    ]
