# Generated by Django 3.2.12 on 2022-02-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_book_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='destination',
            field=models.CharField(choices=[('kpakngu', 'kpakngu')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
