# Generated by Django 3.2.12 on 2022-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='destination',
            field=models.CharField(choices=[('Lokoja', 'Lokoja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('kabba', 'kabba')], max_length=50),
        ),
    ]
