# Generated by Django 3.2.12 on 2022-02-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20220228_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.destination')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.source')),
            ],
        ),
    ]
