# Generated by Django 3.2.12 on 2022-02-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
