# Generated by Django 3.2.12 on 2022-03-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20220302_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(max_length=50),
        ),
    ]
