# Generated by Django 3.2.12 on 2022-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pick_up_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='pick_up_time',
            field=models.TimeField(),
        ),
    ]
