# Generated by Django 3.2.12 on 2022-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20220305_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
