# Generated by Django 3.2.12 on 2022-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_orders_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='booking_id',
            field=models.CharField(default='Dd', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
