# Generated by Django 3.2.12 on 2022-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_orders_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='booking_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
